name: Foo API Test
on:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Lighthouse
      uses: ./
      with:
        device: all
        urls: 'https://chuck-norris-api.netlify.app/'
        tag: GitHub Action (Foo API Test)
